blog/urls.py
from django.urls import path
from blog import views
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings

app_name = 'blog'

urlpatterns = [
    path('', views.posts_home, name='posts_home'),
    path('create/', views.create_post, name='create'),
    path('update/<int:pk>', views.update_post, name='update'),
    path('delete/<int:pk>', views.delete_post, name='delete'),
    path('<slug>/', views.post_detail, name='details'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

trydjango/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
]

blog/models.py
from django.db import models
from django.urls import reverse
from django.db.models.signals import pre_save
from django.utils.text import slugify
from django.conf import settings
from django.utils import timezone
import datetime

class PostManager(models.Manager):
    """
    class overides objects.all manager to prevent the display of future and draft posts
    """
    def active(self, *args, **kwargs):
        return super(PostManager, self).filter(draft=False)

class Post(models.Model):
    """
    class facilitates the creation of post objects
    """
    user = models.ForeignKey(settings.AUTH_USER_MODEL,  on_delete=models.CASCADE, default=1)
    title = models.CharField(max_length=100)
    slug = models.SlugField(unique=True)
    content = models.TextField()
    time_stamp = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    image = models.ImageField(blank=True, null=True, width_field="width_field", height_field="height_field", upload_to='images/')
    height_field = models.IntegerField(default=0)
    width_field = models.IntegerField(default=0)
    draft = models.BooleanField(default=False)
    publish = models.DateField(auto_now_add=False, auto_now=False)

    objects = PostManager()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("blog:details", kwargs={"slug": self.slug})

def create_slug(instance, new_slug=None):
    slug = slugify(instance.title)
    if new_slug is not None:
        slug = new_slug
    querystring = Post.objects.filter(slug=slug).order_by('-pk')
    exists = querystring.exists()
    if exists:
        new_slug = "{} {}".format(slug, querystring.first().id)
        return create_slug(instance, new_slug=new_slug)
    return slug

def pre_save_post_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)

pre_save.connect(pre_save_post_receiver, sender=Post)    

   

blog/forms.py
from blog.models import Post
from django import forms

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'content', 'image', 'publish', 'draft']

blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from blog.models import Post
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.core.exceptions import ObjectDoesNotExist
from django.views import generic
from blog.forms import PostForm
from django.contrib import messages
from django.core.paginator import Paginator, PageNotAnInteger
from urllib.parse import quote_plus
from django.utils import timezone
from django.db.models import Q

def posts_home(request):
    """
    view function gets post saved in teh database
    """
    posts_list = Post.objects.active().order_by('-id')
    if request.user.is_superuser or request.user.is_staff:
        posts_list = Post.objects.all().order_by('-id')
    
    query = request.GET.get("q")
    if query:
        posts_list = posts_list.filter(Q(title__icontains=query) | Q(content__icontains=query) | Q(user__username__icontains=query)).distinct()
    paginator = Paginator(posts_list, 5)
    page = request.GET.get('page')
    
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    context = {
        'posts':posts,
        
    }
    return render(request, 'blog/home.html', context)

def post_detail(request, slug=None):
    """
    view function gets a single post associated with the passed unique slug
    """
    post = get_object_or_404(Post, slug=slug)
    if post.draft:
        if not request.user.is_authenticated or not request.user.is_superuser:
            raise Http404
    elif post.publish>timezone.now().date():
        if not request.user.is_authenticated or not request.user.is_superuser:
            raise Http404
        
    string_share = quote_plus(post.content)
    context = {
        'post': post,
        'string_share': string_share,
    }
    return render(request, 'blog/detail.html', context)

def create_post(request):
    """
    view function handles the creation of new post instances
    """
    if not request.user.is_authenticated:
        raise Http404
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES or None)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.save()
            messages.success(request, "Post Created Successfully")
            return HttpResponseRedirect(post.get_absolute_url())
    else:
        form = PostForm()
        context = {
            "form": form,
        }
    return render(request, 'blog/new_post.html', context)

def update_post(request, pk):
    """
    view function uodates a single post
    """
    if not request.user.is_authenticated:
        raise Http404
    post = get_object_or_404(Post, pk=pk)
    form = PostForm(request.POST or None, request.FILES or None, instance=post)
    if form.is_valid():
        post =form.save(commit=False)
        post.save()
        messages.success(request, "Post Edited Successfully")
        return HttpResponseRedirect(post.get_absolute_url())
    
    context = {
        "form": form,
        "post": post,
    }
    return render(request, 'blog/update.html', context)

def delete_post(request, pk):
    """
    view function handles the deletion of a single post
    """
    if not request.user.is_authenticated:
        raise Http404
    post = get_object_or_404(Post, pk=pk)
    post.delete()
    messages.success(request, "Post Deleted Successfully")
    return redirect('blog:posts_home')

blog/templates/blog/base.html
{% load bootstrap4 %}
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        {% if title %}
        <title>Blogs - {{title}}</title>
        {% else %}
        <title>Blogs</title>
        {% endif %}

        {% block styles %}
            {% bootstrap_css %}
            <link rel="stylesheet" type="text/css" href="{% static 'css/index.css'%}">
        {% endblock %}
        <link href="https://fonts.googleapis.com/css2?family=Montserrat+Alternates:ital@1&display=swap" rel="stylesheet">
        <script src="https://kit.fontawesome.com/79cafd0f3e.js" crossorigin="anonymous"></script>
    </head>
    <body>
        {% include 'blog/navbar.html' %}
        {% block content %}
        {% endblock %}

        {% block scripts %}
            <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
            {% bootstrap_javascript %}
            <script id="dsq-count-scr" src="//blogify-2.disqus.com/count.js" async></script>
        {% endblock %}
    </body>
</html>

blog/templates/blog/detail.html
{% extends 'blog/base.html' %}
{% load urlify %}

{% block content %}
<div class="container" style="margin-top: 20px;">
    <hr>
    <h2 class="text-center">{{post.title}}</h2>
    <hr>
    <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-6">
            {% if messages %}
                {% for message in messages %}
                <p class="alert alert-success">{{ message }}</p>
                {% endfor %}
            {% endif %}
            <div class="card border-info mb-3">
                {% if post.image %}
                    <img src="{{post.image.url}}" class="img-fluid">
                {% endif %}
                
                <div class="card-body">
                    <small style="float: right;" class="text-muted">Posted {{post.publish}} ago by {{post.user}}</br>Updated {{post.updated|timesince}} ago</small>
                    <h3 style="font-style: italic;">{{post.title}}</h3>
                    {% if post.draft %}
                    <span><small class="badge badge-danger">draft</small></span>
                    {% endif %}
                    <hr>
                    <p style="float: left;">{{post.content|linebreaks}}</p>
                    <hr>
                    
                    <div id="disqus_thread"></div>
                    <script>
                    
                    
                    var disqus_config = function () {
                    this.page.url = '{{request.build_abolute_uri }}';
                    this.page.identifier = '{{post.title|urlify}}';
                    };                    
                    (function() { // DON'T EDIT BELOW THIS LINE
                    var d = document, s = d.createElement('script');
                    s.src = 'https://blogify-2.disqus.com/embed.js';
                    s.setAttribute('data-timestamp', +new Date());
                    (d.head || d.body).appendChild(s);
                    })();
                    </script>
                    <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
                    <hr>
                    {% if request.user == post.user %}
                    <div class="row" style="float: left;">
                        <a href="{% url 'blog:update' post.id %}" class="btn btn-info" style="margin-right: 10px;">Edit Post</a>
                        <a href="{% url 'blog:delete' post.id %}" class="btn btn-danger">Delete Post</a>
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="col-md-3"></div>
    </div>
</div>
{% endblock %}

blog/templates/blog/home.html
{% extends 'blog/base.html' %}

{% block content %}
    <div class="container">
        <hr>
        <h1 class="text-center">Welcome to Blogify</h1>
        <hr>
        {% if messages %}
            {% for message in messages %}
            <p class="alert alert-danger">{{ message }}</p>
            {% endfor %}
        {% endif %}
        <div class="col-sm-12">
            {% for post in posts %}
            <div class="row">
                <div class="col-sm-3"></div>
                <div class="col-sm-6">
                    <div class="card border-info mb-5">
                        {% if post.image %}
                        <img src="{{post.image.url}}" class="img-fluid">
                        {% endif %}
                        <div class="card-body">
                            <h6><a href="{{post.get_absolute_url}}">{{post.title|truncatechars:20}}</a><small style="float: right;" class="text-muted">Posted {{post.time_stamp|timesince}} ago by {{post.user}}</small></h6>
                            {% if post.draft %}
                            <span><small class="badge badge-danger">draft</small></span>
                            {% endif %}
                            <p style="float: left; margin-top: 20px;">{{post.content|linebreaks|truncatechars:80}}</p>
                        </div>
                    </div>
                </div>
                <div class="col-sm-3"></div>
                <hr>
            </div>
            {% endfor %}
            <div class="row">
                <div class="col-sm-3"></div>
                <div class="col-sm-6">
                    <div class="pagination">
                        <span class="step-links">
                            {% if posts.has_previous %}
                                <a href="?page=1">&laquo; first</a>
                                <a href="?page={{ posts.previous_page_number }}{% if request.GET.q %}&q={{request.GET.q}}{% endif %}">previous</a>
                            {% endif %}
                    
                            <span class="current">
                                Page {{ posts.number }} of {{ posts.paginator.num_pages }}.
                            </span>
                    
                            {% if posts.has_next %}
                                <a href="?page={{ posts.next_page_number }}{% if request.GET.q %}&q={{request.GET.q}}{% endif %}">next</a>
                                <a href="?page={{ posts.paginator.num_pages }}{% if request.GET.q %}&q={{request.GET.q}}{% endif %}">last &raquo;</a>
                            {% endif %}
                        </span>
                    </div>
                </div>
                <div class="col-sm-3"></div>
            </div>
            
        </div>
    </div>
{% endblock %}

blog/templates/blog/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-info">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
      <a class="navbar-brand" href="{% url 'blog:posts_home' %}">Blogify</a>
      <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
        <li class="nav-item active">
          <a class="nav-link" href="#">About<span class="sr-only">(current)</span></a>
        </li>
      </ul>
      <form class="form-inline my-2 my-lg-0" method='GET' action="">
        <input class="form-control mr-sm-2" type="search" name='q' placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-light my-2 my-sm-0" type="submit" value="search">Search</button>
      </form>
    </div>
  </nav>

blog/templates/blog/new_post.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-6">
            {% if messages %}
                {% for message in messages %}
                <p class="alert alert-success">{{ message }}</p>
                {% endfor %}
            {% endif %}
            <form method="POST" enctype="multipart/form-data">
                {%csrf_token%}
                <fieldset class="form-group"> 
                    <legend class="border-bottom mb-4 text-center">Add New Post</legend>
                    {{form|crispy}}
                </fieldset>
                <div class="row">
                    <div class="col-md-5"></div>
                    <div class="col-md-5">
                        <div class="form-group">
                            <button class="btn btn-outline-info btn-lg" type="submit">Add Post</button>
                        </div>
                    </div>
                    <div class="col-md-2"></div>
                </div>
            </form>
        </div>
        <div class="col-md-3"></div>
    </div>
</div>
{% endblock %}

blog/templates/blog/update.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-6">
            <form method="POST" enctype="multipart/form-data">
                {%csrf_token%}
                <fieldset class="form-group"> 
                    <legend class="border-bottom mb-4 text-center">Edit Post</legend>
                    {{form|crispy}}
                </fieldset>
                <div class="row">
                    <div class="col-md-5"></div>
                    <div class="col-md-5">
                        <div class="form-group">
                            <button class="btn btn-outline-info btn-lg" type="submit">Edit</button>
                        </div>
                    </div>
                    <div class="col-md-2"></div>
                </div>
                
            </form>
        </div>
        <div class="col-md-3"></div>
    </div>
</div>
{% endblock %}